# Simple workflow to build the site using Vite (via pnpm actions) and deploy to GitHub Pages

name: Deploy static content to GitHub Pages

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # A single job called "deploy" as we're just deploying the site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.pages_deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies using pnpm
        run: pnpm install

      - name: Build the project (Vite will output the static result in /dist/)
        run: pnpm run build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' #upload the dist folder, where Vite puts the auto-generated static site files

      - name: Deploy to GitHub Pages
        id: pages_deployment
        uses: actions/deploy-pages@v4
